### ISSUE TITLE
TypeError: Object #<Object> has no method 'forEach'

### ISSUE THREAD

**Issue by johnbeech** [subsidel/octo-credits#1]
I broke it?
```sh
TypeError: Object #<Object> has no method 'forEach'
    at realNamedCredits (/Users/beechj01/workspace/product-monitor/node_modules/octo-credits/index.js:8:12)
    at Request._callback (/Users/beechj01/workspace/product-monitor/node_modules/octo-credits/index.js:46:17)
    at Request.self.callback (/Users/beechj01/workspace/product-monitor/node_modules/request/request.js:354:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/beechj01/workspace/product-monitor/node_modules/request/request.js:1207:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/beechj01/workspace/product-monitor/node_modules/request/request.js:1153:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```
But not sure how. Here's my wrapper:
```js
var creditr = require('octo-credits');

var params = {
  repo: 'johnbeech/product-monitor',
  accessToken: false
};

var instance = function() {};

instance.configure = function(config) {
  params.accessToken = config.octoCredits.accessToken;
  return this;
}

instance.renderHtmlTable = function(req, res) {
  var crediting = creditr(params);

  crediting.retreiveCredits(function(credits) {
    var creditsPage = crediting.format.table(credits);
    res.send(creditsPage);
  });
}

instance.render = function (req, res) {
  var crediting = creditr(params);

  crediting.retreiveCredits(function(credits) {
    res.jsonp(credits);
  });
};

module.exports = instance;
```

**Comment by johnbeech** [comment]
Pasting my access token directly into `params.accessToken` instead of `false` made it work. I'm guessing the code your end doesn't like false accessTokens. Must be bug in my code somewhere.

**Comment by johnbeech** [comment]
Nope, definitely bugs out and crashes, especially when hitting a new URL for the first time. 
```
TypeError: Object #<Object> has no method 'forEach'
    at realNamedCredits (/Users/beechj01/workspace/product-monitor/node_modules/octo-credits/index.js:8:12)
    at Request._callback (/Users/beechj01/workspace/product-monitor/node_modules/octo-credits/index.js:46:17)
    at Request.self.callback (/Users/beechj01/workspace/product-monitor/node_modules/request/request.js:354:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/beechj01/workspace/product-monitor/node_modules/request/request.js:1207:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/beechj01/workspace/product-monitor/node_modules/request/request.js:1153:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```
Restarting the server and hitting the endpoint again works. I've had failures and then successes hitting:
* http://localhost:8080/api/octoCredits/markavian/LD30
* http://localhost:8080/api/octoCredits/johnbeech/product-monitor
* http://localhost:8080/api/octoCredits/subsidel/octo-credits

But I've needed to restart my server each time, I can stick a try-catch around it...

**Comment by Markavian** [comment]
I can't get this to work at all on Windows, same issue, virtually the same error:
```sh
TypeError: Object #<Object> has no method 'forEach'
    at realNamedCredits (C:\Users\Markavian\Work\Local\product-monitor\node_modu
les\octo-credits\index.js:8:12)
    at Request._callback (C:\Users\Markavian\Work\Local\product-monitor\node_mod
ules\octo-credits\index.js:46:17)
    at Request.self.callback (C:\Users\Markavian\Work\Local\product-monitor\node
_modules\request\request.js:354:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\Markavian\Work\Local\product-monitor\node_m
odules\request\request.js:1207:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Users\Markavian\Work\Local\product-monito
r\node_modules\request\request.js:1153:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
```

**Comment by Markavian** [comment]
I, err, upgraded to use release 2.0.0, with the access token, and I got it to get a valid response, but then the next call I made caused the server to crash again. Sad face.

http://localhost:8080/api/octoCredits/markavian/LD26 :
```js
[
  {
    name: "Markavian",
    commits: 27,
    avatar: "https://avatars.githubusercontent.com/u/1431385?v=3",
    html_url: "https://github.com/Markavian"
  }
]
```

**Comment by subsidel** [comment]
*should* be fixed in v3.0.0, that null is due to a breaking api change, the format is now 
```js
crediting.retreiveCredits(function(err, credits) {
    //do stuff
});
```

**Comment by subsidel** [comment]
Re-opening to track.

**Comment by subsidel** [comment]
Closing after confirming that this is fixed in v3 onwards.
