### ISSUE TITLE
Crash while making request to repo

### ISSUE THREAD

**Issue by johnbeech** [subsidel/octo-credits#3]
Random crash:

```js
Message: 'Not Found',
  documentation_url: 'https://developer.github.com/v3' }

TypeError: Cannot call method 'map' of undefined
    at /Users/beechj01/workspace/octo-credits/index.js:75:40
    at Object.format.table (/Users/beechj01/workspace/octo-credits/index.js:90:22)
    at /Users/beechj01/workspace/octo-credits/examples.js:19:44
    at Request._callback (/Users/beechj01/workspace/octo-credits/index.js:55:63)
    at Request.self.callback (/Users/beechj01/workspace/octo-credits/node_modules/request/request.js:354:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/beechj01/workspace/octo-credits/node_modules/request/request.js:1207:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/beechj01/workspace/octo-credits/node_modules/request/request.js:1153:12)
    at IncomingMessage.emit (events.js:117:20)
````

**Comment by subsidel** [comment]
What version was this in?
Message: "Not Found" is the github API saying no to your request. 
This is checked against in v3.0.0 and should handle the error correctly.

**Comment by Markavian** [comment]
So, good news, it doesn't crash any more... I got this response: 
```js
{
error: { }
}
```
The server logged `{}` to the console.

And on refreshing against the server, it returned:

```js
[
    {
        name: "Markavian",
        commits: 63,
        avatar: "https://avatars.githubusercontent.com/u/1431385?v=3",
        html_url: "https://github.com/Markavian"
    },
    {
        name: "John Beech",
        commits: 12,
        avatar: "https://avatars.githubusercontent.com/u/6341696?v=3",
        html_url: "https://github.com/johnbeech"
    },
    {
        name: "Joel Howard",
        commits: 6,
        avatar: "https://avatars.githubusercontent.com/u/1258370?v=3",
        html_url: "https://github.com/subsidel"
    }
]
```
